### ISSUE TITLE
Issue with GraphQL API when linking a model to a collection with the hasMany field type

### ISSUE THREAD

**Issue by thomas4Bitcraft** [statamic-rad-pack/runway#561] opened 2024-07-18 21:19 UTC
### Description

I have a pages collection that uses a replicator fields for the different page modules. In one of the modules is a link to a runway model in Laravel. The problem is, that when I want to fetch the model over GraphQL it does not work and fails with the error: 

```
"errors": [
    {
      "message": "Internal server error",
      "locations": [
        {
          "line": 12,
          "column": 13
        }
      ],
      "path": [
        "entry",
        "modules",
        2,
        "leagues",
        0,
        "id"
      ],
      "extensions": {
        "debugMessage": "Call to a member function resolveGqlValue() on null",
        "file": "/home/vagrant/code/uptogame-cms/vendor/statamic-rad-pack/runway/src/GraphQL/ResourceType.php",
        "line": 52,
... }
]
```

Here is the collection blueprint:
```
title: Page
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: modules
            field:
              type: replicator
              display: Modules
              sets:
                new_module:
                  display: 'New Module'
                  sets:
                    calendar:
                      display: Calendar
                      icon: calendar-date
                      fields:
                        -
                          handle: title
                          field:
                            type: text
                            display: Title
                        -
                          handle: leagues
                          field:
                            resource: league
                            title_format: '{{ name }}'
                            type: has_many
                            display: Leagues
                            create: false
```

And here the query: 

```
query global {
  entry(collection: "pages", slug: "home") {
    ... on Entry_Pages_Page {
      id
      modules {
        ... on Set_Modules_Calendar {
          id
          title
          type
          leagues {
            id
          }
        }
      }
    }
  }
}
```

I was able to fix it temporarily by changing the mentioned function from this:
```
protected function resolver()
    {
        return function ($model, $args, $context, ResolveInfo $info) {
            if (! $model instanceof Model) {
                $resource = Runway::findResource(Str::replace('runway_graphql_types_', '', $info->parentType->name));

                $model = $resource->model()->firstWhere($resource->primaryKey(), $model);
            }

            return $model->resolveGqlValue($info->fieldName);
        };
    } 
```

To that: 
```
protected function resolver()
    {
        return function ($model, $args, $context, ResolveInfo $info) {
            if (! $model instanceof Model) {
                $resource = Runway::findResource(Str::replace('runway_graphql_types_', '', $info->parentType->name));

                $model = $resource->model()->firstWhere($resource->primaryKey(), $model[$resource->primaryKey()]->value());
            }

            return $model->resolveGqlValue($info->fieldName);
        };
    }
```

### Steps to reproduce

-

### Environment

Application Name: Statamic
Laravel Version: 11.15.0
PHP Version: 8.2.7
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.15.0 PRO

Statamic Addons
statamic-rad-pack/runway: 7.6.0

**Comment by thomas4Bitcraft** [comment] 2024-07-29 15:56
@duncanmcclean There is still an error with this field:

```
"errors": [
    {
      "message": "Internal server error",
      "locations": [
        {
          "line": 11,
          "column": 11
        }
      ],
      "path": [
        "entry",
        "modules",
        2,
        "leagues"
      ],
      "extensions": {
        "debugMessage": "Method Statamic\\Fields\\Values::get does not exist.",
        "file": "/var/www/up2game-prod/releases/20240729155022/vendor/statamic/cms/src/Fields/Values.php",
        "line": 102,
        "trace": [
          {
            "file": "/var/www/up2game-prod/releases/20240729155022/vendor/statamic-rad-pack/runway/src/Fieldtypes/HasManyFieldtype.php",
            "line": 76,
            "call": "Statamic\\Fields\\Values::__call()"
          },
          {
            "file": "/var/www/up2game-prod/releases/20240729155022/vendor/statamic/cms/src/GraphQL/Types/ReplicatorSetType.php",
            "line": 35,
            "call": "StatamicRadPack\\Runway\\Fieldtypes\\HasManyFieldtype::StatamicRadPack\\Runway\\Fieldtypes\\{closure}()"
          },
```

**Comment by duncanmcclean** [comment] 2024-07-29 16:01
I'll take another look when I'm back on Runway.

**Comment by duncanmcclean** [comment] 2024-08-06 11:49
Unfortunatley, I can't replicate the error.... in my case `products` is a Has Many field:

![CleanShot 2024-08-06 at 12 47 32](https://github.com/user-attachments/assets/1b73afec-19ab-4d3b-9316-4f2fb9504d76)

Can you provide the GraphQL query you're trying to run? Are you definetly using Runway v7.7.1 or above?

**Comment by duncanmcclean** [comment] 2024-09-04 15:35
I'm going to close this issue for the timebeing since I'm still unable to reproduce the issue.

**Closed by duncanmcclean** 2024-09-04 15:35 UTC
Labels: bug, can't recreate, GraphQL, needs more info
